name: rss_reader
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  xml: ^6.5.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
